# Generated by Django 5.2 on 2026-04-07 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imatge', models.ImageField(blank=True, null=True, upload_to='imatges/')),
                ('llibre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imatges', to='biblio.llibre')),
            ],
        ),
    ]
