# Generated by Django 5.2 on 2026-04-07 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_imatge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imatge',
            name='llibre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imatges', to='biblio.llibre'),
        ),
    ]
